# Javascript Node CircleCI configuration file

version: 2.1
jobs:
  build:
    docker:
      - image: node:24-alpine
    working_directory: ~/build
    steps:
      - run:
          name: Install deployment tools
          command: apk add --no-cache docker-cli git openssh-client
      - checkout
      - run:
          name: Install dependencies
          command: npm ci && npm ci --prefix api
      - run:
          name: Build and verify
          command: npm run build
      - setup_remote_docker
      - run:
          name: Build and push images
          command: |
            docker login -u _json_key -p "$GCRIO_KEY" https://gcr.io
            docker build -t gcr.io/screeps-test/docs:$CIRCLE_BUILD_NUM -f ~/build/Dockerfile ~/build
            docker push gcr.io/screeps-test/docs:$CIRCLE_BUILD_NUM
      - run:
          name: Tag commits
          command: |
            git tag build-$CIRCLE_BUILD_NUM && git push origin --tags

workflows:
  production:
    jobs:
      - build:
          context: production
